### ISSUE TITLE
The list of notes adds the first note to the end again

### ISSUE THREAD

**Issue by Mardekaar** [g0dd4rd/Note-Generator#1]
In the generated list of notes, the first note name is repeated at the end of the list, e.g:
a, b, c, d, e, f, g, a

Thus, the list will contain 8 notes instead of 7.

**Comment by g0dd4rd** [comment]
Does this https://github.com/g0dd4rd/Note-Generator/commit/2801b41d424fb82de97f5c9b9235c683c4973cef fix the issue for you?

**Comment by Mardekaar** [comment]
Yes, it is fixed now.

**Comment by Mardekaar** [comment]
Issue fixed and resolved.
